# Generated by Django 2.0.4 on 2018-04-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_auto_20180414_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermatch',
            name='rank',
            field=models.CharField(choices=[('U', 'Unranked'), ('B', 'Bronze'), ('S', 'Silver'), ('G', 'Gold'), ('P', 'Platinum'), ('D', 'Diamond'), ('M', 'Master'), ('C', 'Challenger')], default='o', max_length=1),
            preserve_default=False,
        ),
    ]
