# Generated by Django 2.0.4 on 2018-04-21 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_auto_20180414_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summoner',
            old_name='accountID',
            new_name='account_id',
        ),
        migrations.RenameField(
            model_name='summoner',
            old_name='profileIconId',
            new_name='icon_id',
        ),
        migrations.RenameField(
            model_name='summoner',
            old_name='summonerLevel',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='summoner',
            old_name='summonerID',
            new_name='summoner_id',
        ),
    ]
