# Generated by Django 2.0.4 on 2018-04-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_playermatch_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='match',
            name='date',
        ),
    ]
