# Generated by Django 2.0.2 on 2018-04-08 16:49
# from .models import *
from django.db import migrations
import cassiopeia as cass

from league.static.python.APIKey import riot_key
from league.static.python import APIKey
cass.set_riot_api_key(riot_key())
cass.set_default_region(cass.Region.europe_west)


def gen_champions(apps, schema_editor):
	# static_champ_list = watcher.static_data.champions(region, tags='all')
	static_champ_list = cass.Champions()
	# champion_keys = static_champ_list['keys']
	# data = static_champ_list['data']
	# noinspection PyPep8Naming
	Champion = apps.get_model('league', 'Champion')
	champ_objects = []
	for champ in static_champ_list:
		# champ = data[name]
		img = 'http://stelar7.no/cdragon/latest/champion-icons/' + str(champ.id) + '.png'
		passive = champ.passive
		passive_img = 'http://ddragon.leagueoflegends.com/cdn/6.24.1/img/passive/' + passive.image_info.full
		Champion.objects.create(champion_id=champ.id, name=champ.name, image=img, title=champ.title,
								passiveName=passive.name, passiveDescription=passive.sanitized_description,
								passiveImage=passive_img).save()


def gen_spells(apps, schema_editor):
	# static_spell_list = watcher.static_data.summoner_spells(region, tags='all')
	static_spell_list = cass.SummonerSpells()
	# spell_objects = []
	# data = static_spell_list['data']
	# noinspection PyPep8Naming
	Spell = apps.get_model('league', 'Spell')
	for spell in static_spell_list:
		img = 'http://ddragon.leagueoflegends.com/cdn/6.24.1/img/spell/' + spell.image.full
		Spell.objects.create(spellID=spell.id, spellKey=spell.key, spellName=spell.name, image=img,
								spellDescription=spell.description).save()


# def gen_runes(apps, schema_editor):
# 	static_rune_list = watcher.static_data.summoner_spells(region, tags='all')


class Migration(migrations.Migration):
	dependencies = [
		('league', '0001_initial'),
	]

	operations = [
		migrations.RunPython(gen_spells),
		migrations.RunPython(gen_champions),
	]
