# Generated by Django 2.0.2 on 2018-04-08 16:49
# from .models import *
from riotwatcher import RiotWatcher

from league.static.python import APIKey


def genChampions():
	key = APIKey.APIKey()
	watcher = RiotWatcher(key)
	region = 'euw1'
	static_champ_list = watcher.static_data.champions(region, tags='all')
	champion_keys = static_champ_list['keys']
	data = static_champ_list['data']
	champ_objects = []
	for key, name in champion_keys.items():
		champ = data[name]
		img = 'http://ddragon.leagueoflegends.com/cdn/6.24.1/img/champion/' + champ['image']['full']
		passive = champ['passive']
		passive_img = 'http://ddragon.leagueoflegends.com/cdn/6.24.1/img/passive/' + passive['image']['full']
		print(passive_img)  # ),name=champ['name'],image=img,title=champ['title'],
		# passiveName=passive['name'],passiveDescription=passive['sanitizedDescription'],
		# passiveImage=passive_img)


genChampions()
