# Generated by Django 2.0.2 on 2018-04-08 16:49
from django.db import migrations
#from .models import *
import APIKey
from riotwatcher import RiotWatcher
from django.db import migrations
def genChampions():
	Key = APIKey.APIKey()
	watcher = RiotWatcher(Key)
	region = 'euw1'
	static_champ_list = watcher.static_data.champions(region, tags = 'all')
	champion_keys = static_champ_list['keys']
	data = static_champ_list['data']
	champ_objects = []
	for key,name in champion_keys.items():
		champ = data[name]
		img = 'http://ddragon.leagueoflegends.com/cdn/6.24.1/img/champion/' + champ['image']['full']
		passive = champ['passive']
		passiveImg = 'http://ddragon.leagueoflegends.com/cdn/6.24.1/img/passive/' + passive['image']['full']
		print(passiveImg)#),name=champ['name'],image=img,title=champ['title'],
								 #passiveName=passive['name'],passiveDescription=passive['sanitizedDescription'],
								 #passiveImage=passiveImg)
genChampions()
